# Generated by Django 3.1.4 on 2021-01-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customermodel_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='default_address',
        ),
    ]
