# Generated by Django 3.1.4 on 2021-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('street_address_1', models.CharField(blank=True, max_length=256)),
                ('street_address_2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
