# Generated by Django 3.1.4 on 2021-01-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210126_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='company_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_2',
        ),
    ]
