# Generated by Django 3.2 on 2021-05-26 06:38

from django.db import migrations
import product.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210526_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=product.models.image_directory_path),
        ),
    ]
