# Generated by Django 3.1.4 on 2021-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_auto_20201211_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customer_addresses', to='core.Address'),
        ),
    ]
