# Generated by Django 3.1.4 on 2021-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210227_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='name',
            field=models.CharField(default='User', max_length=50, verbose_name='User Name'),
        ),
    ]
