# Generated by Django 3.1.4 on 2021-01-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customermodel_addresses'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('unfulfilled', 'Unfulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_price', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4)),
                ('total_order_amount', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.customermodel')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
