# Generated by Django 3.1.4 on 2021-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210126_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
