# Generated by Django 3.1.4 on 2021-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210126_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
